### create a numpy : np.array()

In [2]:
import numpy as np

In [4]:
roll_no=[5,6,47,25,5]
roll_array=np.array(roll_no)
print(roll_array)
type(roll_array)


[ 5  6 47 25  5]


numpy.ndarray

In [5]:
roll_no=np.array([5,6,47,25,5])
print(roll_no)

[ 5  6 47 25  5]


In [6]:
list_1=([5,6,5],[5,3,5],[4,6,9])
np.array(list_1)

array([[5, 6, 5],
       [5, 3, 5],
       [4, 6, 9]])

In [7]:
np.arange(5,68)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67])

In [8]:
np.arange(5,68,8)

array([ 5, 13, 21, 29, 37, 45, 53, 61])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(6,int)

array([0, 0, 0, 0, 0, 0])

In [11]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones(8,int)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [15]:
np.linspace(0,20,15)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

In [22]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### Random number

In [17]:
np.random.random(size=12)

array([0.05887086, 0.69206582, 0.34779093, 0.77663138, 0.84340488,
       0.40162739, 0.9493851 , 0.57812387, 0.27981977, 0.2505533 ,
       0.31152097, 0.34026111])

In [20]:
np.random.rand(2,4)

array([[0.16264182, 0.13341087, 0.75760028, 0.86549116],
       [0.14251462, 0.26711674, 0.75611493, 0.26898697]])

In [23]:
np.random.randn(2,4)

array([[-1.0904738 ,  1.05357624,  0.55152142,  0.10049692],
       [ 0.68336228, -0.28062146, -1.1567473 ,  1.15891418]])

In [24]:
np.random.randint(3,15)

14

In [25]:
np.random.randint(3,15,5)

array([ 5, 11,  9,  5,  7])

In [27]:
m=np.empty((3,3),int)
m

array([[      0,       1,       0],
       [7143521,    1060,       0],
       [    768,   32765, 5439609]])

In [30]:
s=np.arange(5,10)
s

array([5, 6, 7, 8, 9])

In [32]:
r=np.random.randint(1,15,3)
r

array([ 5, 11,  5])

In [33]:
s.min()

5

In [35]:
s.max()

9

In [36]:
s.argmin()

0

In [37]:
s.argmax()

4

In [38]:
s.dtype

dtype('int32')

In [39]:
v=np.eye(4)
v

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
v.T

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
s=np.arange(10,28)
s

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [46]:
s=s.reshape(3,6)
s

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27]])

In [48]:
s=s.reshape(2,3)
#cannot reshape array of size 18 into shape (2,3)


ValueError: cannot reshape array of size 18 into shape (2,3)

In [49]:
s[1]=100
s

array([[ 10,  11,  12,  13,  14,  15],
       [100, 100, 100, 100, 100, 100],
       [ 22,  23,  24,  25,  26,  27]])

In [50]:
s[1:6]

array([[100, 100, 100, 100, 100, 100],
       [ 22,  23,  24,  25,  26,  27]])

In [51]:
ss=s[0:7]
ss

array([[ 10,  11,  12,  13,  14,  15],
       [100, 100, 100, 100, 100, 100],
       [ 22,  23,  24,  25,  26,  27]])

### Two-dimensional array

In [55]:
s=np.array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27]])
s

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27]])

In [56]:
s[2][2]

24

In [57]:
s[1][2]
#indexing

18

In [58]:
s[:,2]

array([12, 18, 24])

In [60]:
s[1:2,2:3]
#slicing

array([[18]])

In [62]:
s+s

array([[20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54]])

In [63]:
np.exp(s)

array([[2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11]])

In [64]:
np.sqrt(s)

array([[3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242]])

In [65]:
np.max(s)

27

In [66]:
np.min(s)

10

In [67]:
np.argmin(s)

0

In [68]:
np.argmin(s)

0

In [69]:
np.std(s)

5.188127472091127

In [70]:
np.var(s)

26.916666666666668

In [71]:
np.mean(s)

18.5

In [73]:
np.round(s,decimals=4)

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27]])

In [76]:
veg=np.array(["carrot","beetroot","potato","carrot","cucumber"])
veg

array(['carrot', 'beetroot', 'potato', 'carrot', 'cucumber'], dtype='<U8')

In [77]:
print("flattened array:\n",np.ndarray.flatten(s))

flattened array:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]


In [5]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
Z=np.arange(10,65)
print (Z)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64]


In [7]:
Z= Z[::-1]
print (Z)

[64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41
 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17
 16 15 14 13 12 11 10]


In [8]:
Z = np.arange(9).reshape(3,3)
print (Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
